import Foundation

/// What the app will do with an action, decided before the model's turn
/// continues. This is the whole safety story of the assistant: it can read
/// freely, and anything that changes the project is shown to the user first.
public enum AgentDecision: Equatable, Sendable {
    case allowed
    case needsApproval(reason: String)
    /// Refused, with the reason handed back to the model as the tool result.
    case refused(reason: String)
}

public enum AgentPolicy {

    /// The largest file worth putting in front of a model or writing by hand.
    public static let maxFileBytes = 256 * 1024

    /// Normalises a path against the project root, or returns nil when it points
    /// outside it.
    ///
    /// The assistant is given a project, not a device. Every path it produces is
    /// relative and is checked here, because a model that has seen `/var/jb/...`
    /// in an error message will happily try to write there.
    public static func relativePath(_ path: String) -> String? {
        var candidate = path.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !candidate.isEmpty else { return nil }
        guard !candidate.hasPrefix("/"), !candidate.hasPrefix("~") else { return nil }
        guard !candidate.contains("\0") else { return nil }
        if candidate.hasPrefix("./") {
            candidate = String(candidate.dropFirst(2))
        }
        let components = candidate.split(separator: "/", omittingEmptySubsequences: true).map(String.init)
        guard !components.isEmpty else { return nil }
        guard !components.contains("..") else { return nil }
        return components.joined(separator: "/")
    }

    /// Build output, not source. Writing into it would produce a change that the
    /// next build silently overwrites.
    public static func isBuildOutput(_ relativePath: String) -> Bool {
        relativePath.hasPrefix("packages/") || relativePath.hasPrefix(".theos/") || relativePath.hasPrefix("obj/")
    }

    public static func decide(_ action: AgentAction, privilegesCanEscalate: Bool) -> AgentDecision {
        switch action {
        case .listFiles, .finish, .readCrashes, .gitStatus, .searchHeaders:
            return .allowed

        case .gitDiff(let path):
            guard let path, !path.isEmpty else { return .allowed }
            guard let relative = relativePath(path) else {
                return .refused(reason: "git_diff only accepts a path inside the project. '\(path)' is not one.")
            }
            _ = relative
            return .allowed

        case .readFile(let path):
            guard let relative = relativePath(path) else {
                return .refused(reason: "read_file only accepts a path inside the project, relative to its root. '\(path)' is not one.")
            }
            guard !isBuildOutput(relative) else {
                return .refused(reason: "'\(relative)' is build output, not source. The files worth reading are the Makefile, control, the Logos source and the filter plist.")
            }
            return .allowed

        case .writeFile(let path, let contents):
            guard let relative = relativePath(path) else {
                return .refused(reason: "write_file only accepts a path inside the project, relative to its root. '\(path)' is not one.")
            }
            guard !isBuildOutput(relative) else {
                return .refused(reason: "'\(relative)' is build output; it is regenerated by every build.")
            }
            guard contents.utf8.count <= maxFileBytes else {
                return .refused(reason: "That file would be \(contents.utf8.count) bytes, which is larger than anything a tweak needs. Write it in smaller pieces.")
            }
            return .needsApproval(reason: "Write \(relative)")

        case .replaceInFile(let path, _, _):
            guard let relative = relativePath(path) else {
                return .refused(reason: "replace_in_file only accepts a path inside the project, relative to its root. '\(path)' is not one.")
            }
            guard !isBuildOutput(relative) else {
                return .refused(reason: "'\(relative)' is build output; it is regenerated by every build.")
            }
            return .needsApproval(reason: "Edit \(relative)")

        case .updateControl(let key, let value):
            return .needsApproval(reason: value == nil ? "Remove \(key) from control" : "Set \(key) in control")

        case .build:
            return .needsApproval(reason: "Run make in the project")

        case .install:
            let note = privilegesCanEscalate
                ? "Install the built package and respring"
                : "Install the built package — this app cannot become root, so this will fail unless the package is installed from a package manager"
            return .needsApproval(reason: note)

        case .unknown(_, let reason):
            return .refused(reason: reason)
        }
    }
}
